-- MySQL Script generated by MySQL Workbench
-- Sat Mar 23 11:09:58 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `nombre` VARCHAR(15) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `rol` VARCHAR(11) NOT NULL,
  `estado` TINYINT NOT NULL,
  `aprobado` TINYINT NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `existencia` INT NOT NULL,
  `aprobado` TINYINT NOT NULL,
  `estado` TINYINT NOT NULL,
  `rechazado` VARCHAR(45) NOT NULL,
  `Categoria_id_categoria` INT NOT NULL,
  `usuario_nombre` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_producto`, `Categoria_id_categoria`),
  INDEX `fk_Producto_Categoria_idx` (`Categoria_id_categoria` ASC) VISIBLE,
  INDEX `fk_producto_usuario1_idx` (`usuario_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_Categoria`
    FOREIGN KEY (`Categoria_id_categoria`)
    REFERENCES `mydb`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_usuario1`
    FOREIGN KEY (`usuario_nombre`)
    REFERENCES `mydb`.`usuario` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cartera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cartera` (
  `id_cartera` INT NOT NULL AUTO_INCREMENT,
  `moneda_local` DOUBLE NOT NULL,
  `moneda_sistema` DOUBLE NOT NULL,
  `usuario_nombre` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_cartera`, `usuario_nombre`),
  INDEX `fk_cartera_usuario1_idx` (`usuario_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_cartera_usuario1`
    FOREIGN KEY (`usuario_nombre`)
    REFERENCES `mydb`.`usuario` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venta` (
  `id_venta` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `total` DOUBLE NOT NULL,
  `id_producto` INT NOT NULL,
  `usuario_comprador` VARCHAR(15) NOT NULL,
  `cantidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_venta`, `usuario_comprador`),
  INDEX `fk_venta_producto1_idx` (`id_producto` ASC) VISIBLE,
  INDEX `fk_venta_usuario1_idx` (`usuario_comprador` ASC) VISIBLE,
  CONSTRAINT `fk_venta_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_usuario1`
    FOREIGN KEY (`usuario_comprador`)
    REFERENCES `mydb`.`usuario` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servicio` (
  `id_servicio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `cantidad_contratos` INT NOT NULL,
  `pago_por_contrato` INT NOT NULL,
  `aprobado` TINYINT NOT NULL,
  `estado` TINYINT NOT NULL,
  `rechazado` VARCHAR(45) NULL,
  `usuario_nombre` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_servicio`, `usuario_nombre`),
  INDEX `fk_servicio_usuario1_idx` (`usuario_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_servicio_usuario1`
    FOREIGN KEY (`usuario_nombre`)
    REFERENCES `mydb`.`usuario` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contrato` (
  `id_contrato` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `servicio_id_servicio` INT NOT NULL,
  `usuario_nombre` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_contrato`, `usuario_nombre`),
  INDEX `fk_contrato_servicio1_idx` (`servicio_id_servicio` ASC) VISIBLE,
  INDEX `fk_contrato_usuario1_idx` (`usuario_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_contrato_servicio1`
    FOREIGN KEY (`servicio_id_servicio`)
    REFERENCES `mydb`.`servicio` (`id_servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_usuario1`
    FOREIGN KEY (`usuario_nombre`)
    REFERENCES `mydb`.`usuario` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reporte` (
  `id_reporte` INT NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(200) NOT NULL,
  `id_producto` INT NOT NULL,
  `reportes` INT NOT NULL,
  PRIMARY KEY (`id_reporte`, `id_producto`),
  INDEX `fk_reporte_producto1_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_reporte_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
