CREATE DATABASE MayaMarket;
USE MayaMarket;

CREATE USER 'Usuario'@'%' IDENTIFIED BY 'Password';
GRANT ALL PRIVILEGES ON CentroClinico.* TO 'Usuario'@'%';

CREATE TABLE rol(
  tipo_rol VARCHAR(12) NOT NULL,
  CONSTRAINT PK_ROL PRIMARY KEY(tipo_rol)
);
CREATE TABLE usuario(
  nombre VARCHAR(45) NOT NULL,
  passwd VARCHAR(45) NOT NULL,
  rol VARCHAR(12) NOT NULL,
  estado BOOLEAN DEFAULT TRUE,
  aprobado BOOLEAN DEFAULT FALSE
  CONSTRAINT PK_USUARIO PRIMARY KEY(nombre)
  CONSTRAINT FK_TO_ROL FOREIGN KEY(rol) REFERENCES rol(tipo_rol)
);

CREATE TABLE cartera(
  id_cartera INT NOT NULL AUTO_INCREMENT,
  moneda_local DOUBLE DEFAULT 500.00
  moneda_sistema DOUBLE DEFAULT 150.00
  usuario VARCHAR(45) NOT NULL,
  CONSTRAINT PK_CARTERA PRIMARY KEY(id_cartera)
  CONSTRAINT FK_TO_USUARIO FOREIGN KEY(usuario) REFERENCES usuario(nombre)
);

CREATE TABLE categoria(
  nombre_categoria VARCHAR(10),
  CONSTRAINT PK_CATEGORIA PRIMARY KEY(nombre_categoria)
);

CREATE TABLE producto(
  id_producto INT NOT NULL AUTO_INCREMENT,
  nombre_producto VARCHAR(45) NOT NULL,
  descripcion VARCHAR(100) NOT NULL,
  imagen VARCHAR(100) NOT NULL,
  precio_producto DOUBLE NOT NULL,
  usuario_vendedor INT NOT NULL,
  existencia INT NOT NULL,
  estado BOOLEAN DEFAULT TRUE,
  aprobado BOOLEAN DEFAULT FALSE,
  categoria VARCHAR(10) NOT NULL,
  CONSTRAINT PK_PRODUCTO PRIMARY KEY(id_producto)
  CONSTRAINT FK_TO_USUARIO FOREIGN KEY(usuario_vendedor) REFERENCES usuario(nombre)
);